### ISSUE TITLE
Prefix same nick not supported

### ISSUE THREAD

**Issue by Nicd** [wee-slack/wee-slack#357]
`weechat.look.prefix_same_nick` is not supported. It seems this was discussed in #56 and implemented in #113 but did not end up in the refactor.

**Comment by liskin** [comment]
This shouldn't actually be implemented on wee-slack's side at all, weechat handles it itself: https://github.com/weechat/weechat/blob/efc7a588d641ea4a29fa9e9860e75dab4a1ec3b6/src/gui/gui-line.c#L143
I suspect it doesn't work with wee-slack because wee-slack doesn't set `prefix_nick_` tags but these are required: https://github.com/weechat/weechat/blob/efc7a588d641ea4a29fa9e9860e75dab4a1ec3b6/src/gui/gui-line.c#L153
weechat-matrix does set those tags and prefix_same_nick (and also prefix_same_nick_middle!) work well in there.

I might submit a PR later but feel free to beat me to it. :-)

**Comment by trygveaa** [comment]
Yeah, I know, but if you do it the correct way, it's impossible to distinguish between multi line messages and multiple messages by the same nick when `prefix_same_nick` is set.

**Comment by liskin** [comment]
Multi line messages are currently being printed with no nick prefix at all, so I don't think that would be an issue.

That being said, I was going to fix that as well, as printing messages with no nick prefix leads to misalignment with `weechat.look.prefix_align` being set to `none`:

![image](https://user-images.githubusercontent.com/300342/119585639-5ced5300-bdcb-11eb-845f-40e003968cb0.png)

**Comment by trygveaa** [comment]
It's a while since i tested this, so I might be misremembering, but iirc the prefix is ignored for subsequent lines when `prefix_nick_` is set and `prefix_same_nick` is used.

**Comment by liskin** [comment]
I'm not actually using `prefix_same_nick`. Sorry, if that caused any confusion. The only reason I'm discussing this here is that while trying to fix the alignment issue, I stumbled upon this and wondered why it's being worked around in wee-slack. And then as you mentioned multiline vs multiple messages, I circled back to my original issue. But the screenshot I posted is unrelated to `prefix_same_nick`.

**Comment by trygveaa** [comment]
Well, I don't want the prefix repeated for subsequent lines, since it makes it look like a new message, rather than a new line in the same message. But maybe we can fill it with the same number of spaces so it aligns.

**Comment by liskin** [comment]
Yeah, that would probably work. It's a bit silly to do all this and then also handle `prefix_same_nick` (and possibly also `prefix_same_nick_middle` if anyone wants that) in wee-slack, but if telling multiline messages apart is a requirement, seems like there's no other way.

Thanks for the quick brainstorming here! :-)

**Comment by trygveaa** [comment]
> Yeah, that would probably work. It's a bit silly to do all this and then also handle `prefix_same_nick` (and possibly also `prefix_same_nick_middle` if anyone wants that) in wee-slack, but if telling multiline messages apart is a requirement, seems like there's no other way.

Yes, I agree, but distinguishing multiline messages is a requirement for me, so this would have to be fixed in weechat as far as I can see.

Though, I don't use `prefix_same_nick` either, so that's less important, but I still think multiline messages should be distinguished when using that.

I've fixed the alignment issue in adb1029.

**Comment by trygveaa** [comment]
With the next release of WeeChat (4.0.0) it will fully support multiline messages. This means that we can use `prefix_nick_` without any issues, so I pushed a change now to do that if the WeeChat version is 4.0.0 or greater.
