### ISSUE TITLE
Documentation refers to `/slack join`, which doesn't work

### ISSUE THREAD

**Issue by tuananh** [wee-slack/wee-slack#362]
OS X

I installed weechat with `--with-python` and then install websocket client with `pip install websocket-client`.

Copy the file to `.weechat/python/autoload` folder and start weechat afterward. Set the token with `/set plugins.var.python.slack.slack_api_token <my-token>`; save and reload.

I did see `python scripts loaded: slack` when weechat starts.

However, `/slack join general` doesn't work and it's showing an error "command not found join"

Could anyone help me point out what i did wrong here?

Thank you.

**Comment by ToxicFrog** [comment]
I think the documentation needs to be updated; you should just be able to `/join #name-of-channel`.

**Comment by tuananh** [comment]
If i type `/join #general`, i get `irc: command "join" must be executed on irc buffer (server or channel)`. `/server list` returns `No server`

**Comment by ToxicFrog** [comment]
Make sure you have a Slack buffer focused. This worked for me:
- switch to buffer 1 (the core buffer)
- press ctrl-X until it says `[python] 1:foo.slack.com` rather than `[weechat]` or `[irc/...]`
- type `/join #testing`
And I ended up in the `#testing` channel on that slack.

If you're already in a channel on that slack, you should have autojoined it when the plugin connected to it, and you can use that instead. If you aren't using merged core buffers in weechat, the foo.slack.com buffer is probably not buffer 1, but it should show up in the buffer list.

**Comment by ToxicFrog** [comment]
Note that Slack connections don't show up in `/server list` even when you are connected to them.

**Comment by tuananh** [comment]
I saw this `[06:36] [1] [core] 1:weechat` ; that means I'm already on core buffer right?

After that, `/join <channel>` stills give me `command "join" must be executed on irc buffer (server or channel)`

**Comment by ToxicFrog** [comment]
That means you're in part of the core buffer that is used for issuing commands to weechat itself. Press ctrl-X until it says `[python]` with the appropriate Slack URL, as explained above, rather than `[core]`; then try it.

**Comment by tuananh** [comment]
It works now. Many thanks.

**Comment by ToxicFrog** [comment]
I'm reopening this because I think there is an actionable issue here: the documentation shouldn't point users to `/slack join` and should make it clear what they need to do to use `/join` instead. Glad you got it working though. :)

**Comment by wongjustin99** [comment]
Still think the second half of @ToxicFrog's suggestion needs to be done -- I just spent 30 minutes trying to figure out the same thing. It'd be great to have a suggestion to Ctrl-X to switch the buffer.
