### ISSUE TITLE
custom slash command: request is fired but I don't get the response

### ISSUE THREAD

**Issue by josegm** [wee-slack/wee-slack#369]
I have a custom slash command which calls a custom API and retrieves some information. I've checked the server logs and the API request is received and processed but I don't get the response on weechat. It works ok if fired from Slack client. Response is just a string.

Any idea?

**Comment by auscompgeek** [comment]
Looks like `handle_chatcommand` hasn't been implemented. Also annoyingly enough, it seems the `chat.command` method is undocumented. But it looks like a response from a slash command ends up in `.response` in the object returned. For example, /invite returns:
```json
{"ok": true, "response": "Ok, invited <@UL9U365DH> to jobs"}
```

An unknown command returns:
```json
{"ok": false, "error": "unknown_command"}
```

A successful slash command without a response:
```json
{"keep_input": false, "ok": true}
```

Also, a broken slash command:
```json
{
 "keep_input": true,
 "ok": false,
 "is_temp": true,
 "error": "400_client_error",
 "response": "Darn - that slash command didn't work. Feel free to give it another go, or you can manage the integration (and view who installed it) at <redacted>"
}
```

I'm not sure what happens if the endpoint returns a more rich response, but I think those end up as normal messages rather than being in the response here.
