### ISSUE TITLE
Don't prioritise bot_id above user in get_sender

### ISSUE THREAD

**Issue by jwheare** [wee-slack/wee-slack#519]
https://github.com/wee-slack/wee-slack/blob/221dfc528d7df5460b5d0014d28a6dd6f733ca7b/wee_slack.py#L2006-L2019

Messages sent by other slack apps using the RTM api via `chat.postMessage` with `as_user=true` will sometimes include a bot_id. Weechat currently renders `slack app name :]` as the sender in these cases. The `bot_id` check should probably occur below the `user` key check in this code to fix this.

We've had reports of this happening for wee-slack users that are interacting with users of our IRCCloud integration: https://twitter.com/IRCCloud/status/971416931373854721

**Comment by tfheen** [comment]
This seems related to https://github.com/wee-slack/wee-slack/pull/518 . I'm currently scratching my head about why this is so and what actually identifies a bot in the Slack API, since there's an element of legacy present.

**Comment by jwheare** [comment]
Yeah it's odd. The documentation:

> Set as_user to true and the authenticated user will appear as the author of the message, ignoring any values provided for username, icon_url, and icon_emoji. Posting as the authenticated user requires the client or the more preferred chat:write:user scopes.

We're using the "client" oauth scope, and always send `as_user=true`, but our messages sometimes appear in slack's own apps with an "APP" badge next to them.

```
chat.postMessage =>
{
    "as_user": "true",
    "channel": "C5AL9T7LG",
    "parse": "full",
    "set_active": "true",
    "text": "test"
}

<= Response
{
    "ok": true,
    "channel": "C5AL9T7LG",
    "message": {
        "bot_id": "B7CL1QHPD",
        "text": "test",
        "ts": "1520615044.000341",
        "type": "message",
        "user": "U024FNSU4"
    },
    "ts": "1520615044.000341"
}

RTM:
{
    "bot_id": "B7CL1QHPD",
    "channel": "C5AL9T7LG",
    "event_ts": "1520615044.000341",
    "team": "T024FNSU2",
    "text": "test",
    "ts": "1520615044.000341",
    "type": "message",
    "user": "U024FNSU4"
}
```

From what I've seen, *actual* bot users don't have a `user` key so it should be safe to flip the order here.

**Comment by jwheare** [comment]
Just found this also: https://medium.com/slack-developer-blog/api-update-new-field-in-api-responses-d23076ea2ef3

> Now a message posted with as_user:true may have both a user ID and a bot ID, which will allow clients to label messages clearly as coming from a user, but through an app or bot.

**Comment by tfheen** [comment]
Thanks, looks like we need to swap this around then.

**Comment by tfheen** [comment]
I think we format those correctly now, please let us know if you still see a problem.

**Comment by jwheare** [comment]
Thanks for the quick response! Will let you know.

**Comment by dineshsliit** [comment]
Hi Guys,

i am also facing this issue while triggering a slack direct_message event in Botkit. I was trying to paste a message in to slack using chat.postMessage. There i used as_user = true to see my message is posted as the user. Its working but next thing i wanted is to trigger another event in bot kit as a user's event. But it was not triggered even if the message was pasted as the user. So i checked the response object and found there is bot_id element not the user_id. So that mislead the next event triggering since it needs user_id as a input. Anyway i removed the bot_id and replace it with user_id before send it to the next event. So it solved my issue. But i think its not a good solution when there are more complex situations. So any other solution for this? 

`controller.on('direct_message,direct_mention,mention', function (bot, message) {

if (myJson.hasOwnProperty('bot_id')) {

    var key = "bot_id";
    delete message[key];

    console.log(message);

    var key = "client_msg_id";
    message[key] = message.user;

    console.log(message);
  }

  NextMethod ( bot , message , function ( err ) {  
    if (!err) {

     NextMethodCall(message);
     
    }
    else {
        console.log(err);
    }
  }

}`
