### ISSUE TITLE
/slack back/away not reliable

### ISSUE THREAD

**Issue by leofiore** [wee-slack/wee-slack#565]
weechat 1.9.1, wee_slack paired with master. OSX Yosemiet (10.10.5)

a while ago the `away`/`back` command were broken, then fixed, then now broken again. I'm not sure why this keeps happening. The only error i receive on the weechat buffer (not the slack-debug one) is currently

```
09:52 python: stdout/stderr: Traceback (most recent call last):
09:52 python: stdout/stderr:   File "/Users/leonardo/.weechat/python/autoload/wee_slack.py", line 509, in handle_next
09:52 python: stdout/stderr:     EVENTROUTER.handle_next()
09:52 python: stdout/stderr:   File "/Users/leonardo/.weechat/python/autoload/wee_slack.py", line 499, in handle_next
09:52 python: stdout/stderr:     raise ProcessNotImplemented(function_name)
09:52 python: stdout/stderr: ProcessNotImplemented: userssetPresence
```

The traceback appears only using `/slack back` or `/slack away` commands when using a slack buffer.

**Comment by teemupulliainen** [comment]
Are you by any chance logged in to Slack somewhere else? Setting status by "/slack away|back" seems to not work for me while logged in via the web interface. Might be a feature. 

I'm also getting the same error every time, no matter whether the status is changed or not. 

Just plain /away support doesn't seem to be implemented currently, even if it has once been:

```
def (data, away_command_cb(data, current_buffer, args):
    # TODO: reimplement all.. maybe
```

**Comment by trygveaa** [comment]
What do you mean by being not reliable or broken? Does the presence just not change? Is it a problem both with away and back? When I'm running `/slack away`, I see both in the official client and in wee-slack that I'm set to away, and when I run `/slack back` I'm set to active again.

Note that the slack API doesn't have a command for setting you to active, you can only set presence to `auto` or `away`. On auto, slack decides if you're active or away. I'm not sure exactly how that heuristic is, but I think it sets you to active if you type something (to trigger the typing message in wee-slack you have to type more than 8 characters, not start the line with `/` and don't have it disabled).

The traceback message is just because we don't implement the callback for users.setPresence. It's not a problem.

> Just plain /away support doesn't seem to be implemented currently

It is supported. It calls `/slack back` when run without a message, and `/slack away` if you pass a message.

**Comment by teemupulliainen** [comment]
> On auto, slack decides if you're active or away. I'm not sure exactly how that heuristic is, but I think it sets you to active if you type something

Thanks! I believe this was what caused the confusion, for me at least. I actually read about this, but still didn't come to think about it :) 

> [/away] is supported. It calls /slack back when run without a message, and /slack away if you pass a message.

Yeah, you're right. The "automatic" away handling confused here as well. In addition, setting away with screen_away.pl doesn't seem to work but that's probably caused by something else entirely (such as slack not appearing as a "server" in Weechat or some such).

**Comment by trygveaa** [comment]
> In addition, setting away with screen_away.pl doesn't seem to work but that's probably caused by something else entirely (such as slack not appearing as a "server" in Weechat or some such).

Yes, from what I see in that script, it queries weechat for the `irc_server` list, and loops over that. The slack servers are not part of that list (I'm not sure if they could be).

**Comment by Kudlaty01** [comment]
From my observation slack server accepts user back from being away with presence is set to `auto` when a message is sent to any slack buffer (may be slackbot and even own-self).
My workaround is:
- install [cron script](https://weechat.org/scripts/source/cron.py.html/), best by `/script install cron.py`
- add a cron job like:`/cron add */10 8-17 * * * * python.<slack-domain>.slack.com.<username> command hi`

Please let me know if it works for you
