### ISSUE TITLE
Cannot ping name with apostrophe

### ISSUE THREAD

**Issue by antoyo** [wee-slack/wee-slack#618]
Hi.
When I try to ping someone who has an aspostrophe in his name like `@O'Connor`, it does not work, as if wee-slack is removing the characters after the apostrophe: it shows `@O'`.
Thanks to fix this issue.

**Comment by pasja** [comment]
I just pushed a commit to fix this.

I would be awesome to get some specs about the list of accepted characters from the slack api docs.
So far I only found this: https://api.slack.com/types/user which is less then awesome.

Until then we have to play that whack-a-mole with names...

**Comment by trygveaa** [comment]
Yeah, would be nice if they documented this. But since they don't, I tested all of the ascii characters.

Currently, these are allowed: `0-9 A-Za-z'(),-./;[]_{}`
(note that space is included, but wee-slack strips away space)

And these are not allowed: ``!"#$%&*+:<=>?@\^`|~``

I don't know which non-ascii characters are allowed, but I presume just going with `\w` with unicode enabled is good enough for those.
