### ISSUE TITLE
History is re-loaded every once in a while

### ISSUE THREAD

**Issue by matthijskooijman** [wee-slack/wee-slack#629]
It seems that every once in a while, wee-slack forgets about a channel's (or private chat's) history. This means that when I switch to the buffer, wee-slack first has to get the channel history before I can see new messages.

This is a problem because:
 - Getting the channel history takes a while, so I have to wait
 - I have a script that forwards highlights to another machine to show them on my desktop, so old highlights get shown again.

I realize that lazily loading history is the default, but I have `plugins.var.python.slack.background_load_all_history` set to `true`, which I would understand to mean to automatically load all history on load, and then also keep it in memory.

It could be that my highlight script is not processing input correctly. I'm doing this (in Python):

        w.hook_print("", "notify_message",   "", 1, "on_msg", "")
        w.hook_print("", "notify_private",   "", 1, "on_msg", "private")
        w.hook_print("", "notify_highlight", "", 1, "on_msg", "")

I looked through the weechat API docs, but could not see a way to distinguish between new messages and older messages obtained from history. It could be that the slowness I'm seeing when loading the history is partly because of my highlight script that has to process all these highlights, so if there is some way to make this distinction, that would be great (but that would not fix the actual subject of this issue, namely that history is not kept in memory).

Given this behaviour, I'm wondering if highlights are correctly processed by this script when a buffer's history is dropped, before I open the buffer again?

All this is observed using 0eaf9ed4057f4adbfeb57289f7cc12774027a9aa (about a month old, slightly older than v2.1.0) but the commit log does not show any commits that would obviously fix this.

This issue is tangentially related to #627 (which asks for dropping the entire history handling and just use normal weechat logging). Fixing that would workaround this issue, I think.

**Comment by matthijskooijman** [comment]
Great, the new-marking is indeed fixed now; my notifications don't trigger erronously anymore. This also greatly speeds up the history loading.

Shall we leave this issue open for the other bug, where background loading does not happen on a websocket reconnect?

**Comment by trygveaa** [comment]
> Shall we leave this issue open for the other bug, where background loading does not happen on a websocket reconnect?

Sure, there isn't any other open issue for it as far as I know.

**Comment by Zolotkey** [comment]
I am having a similar issue, with merged buffers of 2-3 channels. It will update all the channels in real time which is what I want. ex: I am in channel2..
```
#channel1 <user> blah
#channel2 <user2> text
#channel1 <user3> text
```

But when I move to the next channel in the buffer so I can reply it loads its history and then I lose the history of the other 2 channels. 
```
#channel1 <user0> old message
#channel1 <user> blah
#channel1 <user3> text
```

Is there a way to fix that?

**Comment by trygveaa** [comment]
@Zolotkey: To fix that issue we'll have to reload history differently when wee-slack reconnects. Now it just throws away the old history, and prints the new it receives. Instead, we should probably check which messages from the new history we are missing, and only print those.

Though, if we do that I'm not sure how we should show that wee-slack is reconnecting and loading messages. Since we wouldn't remove the old messages, we probably can't just show "getting channel history" in the buffer like we do now.

**Comment by ta** [comment]
@trygveaa In terms of showing that a history-reload is in progress, wouldn't some statusbar item be a perfect fit?

**Comment by trygveaa** [comment]
@ta: Do you mean a new statusbar item, or an existing one?

If we create a new item, I think users would have to add it to the statusbar themselves, which means not all users will see it. I'm not sure if we can, or want to, change the statusbar items for the user in the script.

As for the existing items, I don't know of a reliable way to change the info in them. weechat-matrix does it in one way, but that creates conflicts with other python scripts (see https://github.com/poljar/weechat-matrix/issues/54).

So showing the info in the status bar would be nice, but I don't know of a good way to do it.

**Comment by ta** [comment]
@trygveaa I'm relatively new to both weechat and weeslack, so I dont necessarily understand the implications - from a UI/UX standpoint it seemed at good idea :)

I noticed that you are able to change the channel name prefix (when someone is typing) in buflist... maybe it is possible to indicate a history-reload in progress by setting another prefix? If we let the imagination run wild, it could maybe even be a throbber of some sort ;)

**Comment by trygveaa** [comment]
> from a UI/UX standpoint it seemed a good idea :)

Yeah, I agree there, so thanks for the suggestion.

> I noticed that you are able to change the channel name prefix (when someone is typing) in buflist... maybe it is possible to indicate a history-reload in progress by setting another prefix? If we let the imagination run wild, it could maybe even be a throbber of some sort ;)

Hm, an issue with that is that it is done by actually changing the buffer name, which has some side effects, so there's a config option to disable that behavior. Since it is a part of the buffer name, we can't use it to display some text either, just a character (well, technically the buffer name can be whatever we want, but I think it would be impractical to include more in it). It might not be clear what that character means.

**Comment by aereaux** [comment]
How difficult would it be to fix the background loading issue?  I don't understand the codebase that well, but might it be sufficient to call SlackChannel.check_should_open somewhere when we reconnect?  Also, should I create a new issue just for this?

**Comment by trygveaa** [comment]
> How difficult would it be to fix the background loading issue? I don't understand the codebase that well, but might it be sufficient to call SlackChannel.check_should_open somewhere when we reconnect?

I think I tried to solve too much last time I looked at this. I wanted to only load history since the time of disconnection, show fetching of history in a better way, and solve some related issues (open threads not working after reconnection and the one about merged buffers mentioned above). But as a starting point, we could probably run `check_should_open` after reconnection, yes. That would at least trigger loading the history so you don't have to wait for it after switching to a buffer.

> Also, should I create a new issue just for this?

This is the main thing this issue covers, so I don't see a need for a new issue for this.

**Comment by trygveaa** [comment]
> There is a bug that background_load_all_history isn't honored when this happens.

This has now been fixed.

> I have a script that forwards highlights to another machine to show them on my desktop, so old highlights get shown again.

I forgot that this was mentioned in this issue. This is still a problem, so I'll reopen. I'll fix this by disabling print hooks when reprinting history.

**Comment by trygveaa** [comment]
> I have a script that forwards highlights to another machine to show them on my desktop, so old highlights get shown again.

This has now been fixed.

> I am having a similar issue, with merged buffers of 2-3 channels [...] But when I move to the next channel in the buffer so I can reply it loads its history and then I lose the history of the other 2 channels.

@Zolotkey: This issue is still present. I opened a new issue for it: #779
