### ISSUE TITLE
Log file has multiple copies of the same message after fetching history

### ISSUE THREAD

**Issue by mtfurlan** [wee-slack/wee-slack#663]
There are several copies of the same conversation in the log file, because it's written every time wee-slack gets channel history.
```
~/.weechat/logs$ ag "2018-11-25 00:00:02.*cambot"
python.i3detroit.slack.com.#statusbots.weechatlog
3157:2018-11-25 00:00:02        cambot :]       Camera system disk is 95% full (3468G of 3667G). 20.0 hours (43.6 GB) were recorded yesterday.
3362:2018-11-25 00:00:02        cambot :]       Camera system disk is 95% full (3468G of 3667G). 20.0 hours (43.6 GB) were recorded yesterday.
3559:2018-11-25 00:00:02        cambot :]       Camera system disk is 95% full (3468G of 3667G). 20.0 hours (43.6 GB) were recorded yesterday.
```
What can we do to not have duplicate messages in the log file?

**Comment by mtfurlan** [comment]
Related issue:
BACKLOG_SIZE is set to 200, so if more than 200 messages are sent while you're offline, you miss messages, correct?

https://api.slack.com/methods/channels.history
It seems like a better way would be to use the `oldest` argument instead of `count`, or possibly both if you want to batch the history requests.

This would require logging what messages have been received, which is why I stopped making a second issue and am just putting it here.

**Comment by trygveaa** [comment]
Backlog messages are no longer appended to the log file. This means that you shouldn't get duplicate entries unless you have set `background_load_all_history` to true and reload the plugin when you have unread messages (and if so, only the unread messages are duplicated).

One thing to note is that if you read messages in other Slack clients while wee-slack is not running, those messages will never be printed to the log. I assume most people either keep wee-slack running all the time, or don't use other clients while wee-slack isn't running, so hopefully that won't be an issue.

Regarding your second question, yes if more than 200 messages are sent in one channel while you are offline you will miss messages. Using the `oldest` argument doesn't help though, because the history size is always capped by the `count` argument, and that is set to `100` if not given. Additionally, if we set `oldest` to the last read message, we won't get any older messages, which isn't what we want.

To fix that, we would have to paginate through `channels.history` until we reach the last message we read. I created a new issue, #694, for tracking it. I always keep wee-slack running, so it's probably not something I will fix for a while, but pull requests are welcome.

**Comment by moorchegue** [comment]
I'm testing the current master (e00965c). It seems that now only the messages that have been sent by me are duplicated in the chat log. Happy to help debug this if it's not easily reproducible.

**Comment by trygveaa** [comment]
@moorchegue: I couldn't reproduce that issue, but I found some other bugs which possibly are related. Try again with the newest master and see if you still experience the issue.

**Comment by moorchegue** [comment]
I guess those were related, it works perfectly well now, thanks a lot!
