### ISSUE TITLE
Hide or customize internal buffers list

### ISSUE THREAD

**Issue by kpko** [wee-slack/wee-slack#696]
Hi,

I try to use weechat-slack in combination with the buffers.pl plugin. Since weechat-slack provides its own list now, I have two lists with my slack channels and users. I didn't find any way to hide or disable the list from weechat-slack in order to use the list from buffers.pl. Am I missing something here?

I want to use buffers.pl because I would like to customize the appearance of the list, i.e. the position (top/bottom instead of left) and coloring.

Thanks!

**Comment by trygveaa** [comment]
wee-slack doesn't provide any list. The second list you're seeing is `buflist`, which is a part of weechat since version 1.8. It replaces the `buffers.pl` script, which is obsolete and shouldn't be used anymore. See the release notes: https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v1.8_buflist_plugin

`buflist` also supports customizing position and coloring.

**Comment by kpko** [comment]
Ah, stuff starts to make sense now. I'm using weechat solely for use with slack so I didn't know it's included in weechat. 

Thank you very much! :-)
