### ISSUE TITLE
Invite user to private channel?

### ISSUE THREAD

**Issue by jferg-newcontext** [wee-slack/wee-slack#698]
I figure I'm probably just missing something, but how can I invite another user to a private channel using wee-slack?  Normally (in the standard client), I would just @-mention the user in channel and would be prompted to invite them.  However, when I do the same in wee-slack, I get:

```
2019-06-10 15:10:28     jferg   @[user] - You should join this channel.  
2019-06-10 15:10:28     Slackbot        You mentioned @[user], but they’re not in this private channel.
2019-06-10 15:10:28             You may want to invite them.
```
I've tried using both: 
```
/slack slash /invite @[user]
/slack slash /invite @[user] &[channel]
```
and neither triggers so much as an error message, but it doesn't seem to invite them, either.  Can anyone help me out here?

**Comment by auscompgeek** [comment]
Does `/slack slash /invite <username>` work?

**Comment by jferg-newcontext** [comment]
`/slack slash /invite OtherUser` does not seem to work either.

**Comment by auscompgeek** [comment]
I think the invite raw slash command requires the old form usernames, which you may not be seeing. Try /whois'ing someone with #700 and use their username to invite them.

Someone will need to eventually implement a real `/invite` command, but this workaround should work, from what I recall.

**Comment by trygveaa** [comment]
I've now added support for `/invite`, and fixed `/slack slash /invite`.

Note that if you include the channel name for a private channel in the command, you have to use a different prefix for the channel for the two commands, `/invite nick &private-channel` and `/slack slash /invite nick #private-channel`. This is because `/slack slash` doesn't accept the id to a channel, it only accepts the name, and slacks server doesn't know about the & prefix, that only uses #-prefixes.
