### ISSUE TITLE
Make buffer names `slack.subdomain.#name`

### ISSUE THREAD

**Issue by auscompgeek** [wee-slack/wee-slack#709]
We have `plugins.var.python.slack.short_buffer_names` to set buffer names to `subdomain.#name` instead of `subdomain.slack.com.#name`. However, I would prefer my buffer names to be `slack.subdomain.#name` to follow weechat's usual buffer namespacing.

**Comment by trygveaa** [comment]
I did this change a long time ago in PR #208, but it was reverted in b7b6f7dec92463810548c5760c7cbbddee0c1418. I'm not sure what issue @rawdigits had with it.

We could try again, as much of the code has changed since then. `short_buffer_names` didn't exist when I did that change for instance, but since that exists now and works fine, I would think `slack.subdomain` would work fine too.
