### ISSUE TITLE
Grouping of channels

### ISSUE THREAD

**Issue by Atcold** [wee-slack/wee-slack#712]
Right now I have all slack servers grouped together, below a list of channels with the same name.
I don't know what channel belongs to what server.
Is it possible to stop this automatic grouping of slack servers?

Even setting `irc.look.server_buffer = independent` does nothing to the slack servers (while it works just fine for my IRC servers).

Right now I cannot tell which of the three `#general` channels is which.

**Comment by bdesham** [comment]
If you’re able and willing to install the [weechat-autosort](https://github.com/de-vri-es/weechat-autosort) script, that should take care of the issue, even if you just leave it at its default configuration.

**Comment by Atcold** [comment]
Oh, okay. Why isn't this already part of the main script?

**Comment by Lillecarl** [comment]
Hi!

As you see on this printscreen with irc.look.server_buffer set as independent and the weechat autosoft it looks rather iffy.

https://imgur.com/Z0oIrsg

As you see the slack stuff is most certainly at the bottom, but since they're indented under rizon it doesn't look right.

**Comment by trygveaa** [comment]
I think the issue here is that previously, wee-slack only merged the channels when `irc.look.server_buffer` was set to `merge_with_core`, but didn't unmerge them when it was set to `indepentent`. This meant that if you had stored a layout with the buffers merged, you had to unmerge them manually.

Now, wee-slack merges and unmerges the buffers when you change the `irc.look.server_buffer` option.

**Comment by Lillecarl** [comment]
@trygveaa Awesome, thanks! :)
