### ISSUE TITLE
buffer_notify_default is not respected

### ISSUE THREAD

**Issue by apetresc** [wee-slack/wee-slack#746]
I _believe_ this only started happening a few weeks ago, but it's possible I somehow missed it before.

Weechat has a setting in `weechat.conf`'s `[look]` section called `buffer_notify_default` which specifies which types of events (messages, highlights, all, etc) trigger a notify event. It appears that wee-slack manually overrides this setting to `all`. This is annoying for two reasons:

1. The default value isn't respected, obviously
2. More importantly (for me, because I use `all` anyway) is that wee-slack is somehow inserting entries into `weechat.conf` `[notify]` for *every single buffer* it opens. So I have a giant block like this:
```
[notify]
python.***.slack.com.#announcements_ = all
python.***.slack.com.#askpeople = all
python.***.slack.com.#aws-support = all
python.***.slack.com.#cloud = all
python.***.slack.com.#delivery = all
python.***.slack.com.#engineering = all
python.***.slack.com.#golang = all
... [dozens more] ...
``` 
This is annoying because I like to version my dotfiles and this triggers a change every single time someone opens a new chat on Slack.

Is there a way to prevent wee-slack from taking this approach?

**Comment by trygveaa** [comment]
This started happening in weechat 2.6 with the fix for https://github.com/weechat/weechat/issues/1390.

The reason wee-slack sets notify levels is to support muted channels. But wee-slack should preferably only set it for the muted channels, not all. However because a channel may have been changed from muted to unmuted in another client while wee-slack was not running, and the level is stored in weechat.conf, we have to set it to all if this happens. That would at least limit the list to channels which are muted or have been muted once.

**Comment by Ram-Z** [comment]
> However because a channel may have been changed from muted to unmuted in another client while wee-slack was not running, and the level is stored in weechat.conf, we have to set it to all if this happens.

Can it not be unset/deleted when this happens? This would then revert to the default value.

**Comment by trygveaa** [comment]
I don't think you can remove a buffer property once it's been set. Is that possible?

**Comment by Ram-Z** [comment]
I must admit, I didn't check, I just assumed that that would be possible.

I'm able to call `/unset weechat.notify.python.<company>.#<channel>`, call `/save` and it's gone from the settings. Not sure if possible from scripts.

**Comment by trygveaa** [comment]
Right, there's no script function for unsetting, but it is possible to run the `/unset` command from a script.

**Comment by trygveaa** [comment]
Wee-slack now unsets the notify level for unmuted buffers instead of setting it to all. Thus, the default value is respected, and you don't get config values for unmuted buffers.

This fix is not perfect because you still get config values for muted buffers, and since wee-slack is overriding the notify level you can't override it yourself for specific buffers. A potential solution to this could be to set notify level for each line instead of setting notify level for the buffer. I might do this in the future, though it's a breaking change, because if wee-slack doesn't change the notify level at all anymore, any muted channels from earlier versions of wee-slack would remain with the old notify level, so you won't see messages if you unmute it. I.e. you would have to remove the notify levels yourself. Though, I guess this could be solved if we stored the previous wee-slack version loaded, and remove the notify levels when you upgrade.
