### ISSUE TITLE
[bug?] Wee-slack with urlbar plugin

### ISSUE THREAD

**Issue by xmadscientist** [wee-slack/wee-slack#756]
When using wees-slack with the urlbar plugin, urls have to keep reloading every time I start an instance of weeslack. 

So when I start a new instance, all urls from all chat history (as far back as it can go) get loaded into the urlbar. Combined with a URL shortener, it causes a. few minutes of complete unresponsiveness in weechat.

Not sure if it's the behaviour of wee-slack's history loading or urlbar.

**Comment by trygveaa** [comment]
I don't think there is anything wee-slack can do about this, apart from not printing history at all when you load it, since the urlbar script listens for all printed lines. It seems like lines loaded from the log files in irc-channels doesn't trigger it, but I don't know if wee-slack can print lines like that.

The urlbar script could be changed to only listen for lines with specific tags, or ignore lines with specific tags.

> Combined with a URL shortener, it causes a. few minutes of complete unresponsiveness in weechat.

If the url shortener causes unresponsiveness, it should probably be changed to be non-blocking. (Unfortunately, wee-slack isn't non-blocking in all cases either, which can be noticed with large teams, but it doesn't sound like that's your issue).

**Comment by trygveaa** [comment]
Correction, we can do this by setting `print_hooks_enabled` for the buffer to `0` while the history is loaded.
