### ISSUE TITLE
Make websocket client use the same connection as the web client

### ISSUE THREAD

**Issue by tobocop2** [wee-slack/wee-slack#777]
Due to corporate firewall restrictions, I am unable to connect to the websocket url used by this plugin. It would awesome if this could work with the same websocket url that the web client uses. I think that this would be a great feature for anyone that would like to use this plugin with strict firewall restrictions.  I have no idea how much of an effort this would be, but I figure it makes sense to submit this issue as a feature request.

**Comment by trygveaa** [comment]
Generally I prefer using the official API whenever possible. If we were to use the same connection as the web client uses instead of the one provided by the official API, things could break at any moment without notice.

Additionally, we would have to reverse engineer it to figure out how we could connect to it. Just trying to connect to it with a token doesn't work.

I also really doubt it can be used with OAuth tokens, which means we have to support both types of websocket connections which adds complexity and makes the usage harder to understand for users.

So I'm sorry to say that I don't think this is worth doing, and will close this as a wontfix.
