### ISSUE TITLE
Load list of DMs and MPDMs

### ISSUE THREAD

**Issue by nickwynja** [wee-slack/wee-slack#874]
Thanks for the update to using the new session tokens! I can finally try using wee-slack again.

_Originally posted by @trygveaa in https://github.com/wee-slack/wee-slack/issues/844#issuecomment-1250341711_:
> Unfortunately the API doesn't return if a DM or MPDM is open anymore, which caused no DMs and all MPDMs to open on start. It's now changed to only open the DMs and MPDMs with unread messages.

I want to caveat my issue with saying that I'm not very familiar with how weechat works overall; still learning. I don't think I'd need the DMs and MPDMs to show as open but I'm interested at least a list of all of the DMs and MPDMs "available" so I can tab complete them with a `/go` command.

**Comment by nickwynja** [comment]
Learning fast. Seems like I can do this with `/query` as long as I'm in a slack buffer.

**Comment by trygveaa** [comment]
Yes, you can use `/query` from any buffer on the same slack team to open a DM or group DM. You can get a list of all the users in the team with `/slack users`, so that would be all the DMs you can open, and group DMs is any combination of these users by comma separating the names, like `/query user1,user2`.
