### ISSUE TITLE
Direct messages not showing up on login after updating wee_slack.py

### ISSUE THREAD

**Issue by jamespeapen** [wee-slack/wee-slack#875]
Thanks for a great plugin! I was using it without any issue until I needed the update when `rtm.start` broke and I could no longer connect to slack. I updated `wee_slack.py` to 7a9aa20 and after opening weechat now, the buflist no longer shows any direct messages - only channels. Any that I open with `/slack talk` are closed again when reopening weechat. I tried what was suggested in https://github.com/wee-slack/wee-slack/issues/602, but there are no messages printed to the core buffer. I don't have any plugins that close buffers.

**Comment by trygveaa** [comment]
We got the info about which DMs were open from the `rtm.start` endpoint, so this is a cause of moving away from that. I thought we couldn't get this info from any API anymore, but I checked again now and it turns out we can (so either they've added it recently, or I've missed it because we can't get it from the list of DMs anymore, we have to query each one individually).

So I'll fix this (probably tomorrow).

**Comment by jamespeapen** [comment]
Thanks!

**Comment by wommel** [comment]
Any chance on getting the fix released?

**Comment by trygveaa** [comment]
@wommel: Yes, sure, it's released as version 2.9.1 now.
